version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - dynamodb-local
    environment:
      - FLASK_APP=run.py
      - FLASK_RUN_HOST=0.0.0.0
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
